package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"text/template"
	"time"

	"github.com/isan-rivkin/surf/lib/awsu"
	log "github.com/sirupsen/logrus"
)

const (
	templateData = `package cloudformationgenerated

/*
THIS FILE WAS AUTO GENERATED AT {{ .now }}

Do not edit this file, run "go generate" to re-generate this file with an
updated resources of CloudFormation list.
*/

// resource types https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
type generatedCCResourceProperty struct {
	//service-provider::service-name::data-type-name
	ServiceProvider          string
	ServiceName              string
	DataTypeName             string
	ResourceProvisioningType string
}

var GenCloudformationProperties = []generatedCCResourceProperty{ 
	{{ range $i, $r := .resources -}}
	{
		ServiceProvider: "{{ $r.ServiceProvider }}",
		ServiceName: "{{ $r.ServiceName }}",
		DataTypeName: "{{ $r.DataTypeName}}",
		ResourceProvisioningType: "{{ $r.ResourceProvisioningType }}",
	},
	{{ end -}}
}`
)

func createFile(args map[string]interface{}) {
	tmpl := template.Must(template.New("").Parse(templateData))
	buf := bytes.Buffer{}

	if err := tmpl.Execute(&buf, args); err != nil {
		panic(err)
	}

	fileBytes, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Errorf("formatting go source: %w", err))
	}

	newFile := "./lib/awsu/cloudformationgenerated/cloudformation_resources.gen.go"

	_ = ioutil.WriteFile(newFile, fileBytes, 0644)
	fmt.Printf("Generated file: %s\n", newFile)
}

func main() {
	log.Info("running code generation for cloudformation resources")
	auth, err := awsu.NewSessionInput("", "")
	if err != nil {
		panic(fmt.Errorf("creating session in AWS: %w", err))
	}
	cfClient, err := awsu.NewCloudFormation(auth)
	resp, err := awsu.NewCloudFormationAPI(cfClient).GetAllSupportedCloudControlAPIResources()
	if err != nil {
		panic(fmt.Errorf("getting all supported cloud control api resources: %w", err))
	}
	resources, err := resp.GetResources()
	if err != nil {
		panic(fmt.Errorf("parsing resources: %w", err))
	}

	args := map[string]interface{}{
		"resources": resources,
		"now":       time.Now().Format("2006-01-02 15:04:05"),
	}

	createFile(args)
}
